### ISSUE TITLE
some minor questions

### ISSUE THREAD

**Issue by frostworx** [Patrick762/streamdeckapi#8]
Hi there.
Just found your [hassio-streamdeck project](https://github.com/Patrick762/hassio-streamdeck) via built-in HACS "news".
Thank you very much for working on this very promising project!

I just started a WIP streamdeckapi `PKGBUILD` for Arch Linux and got some minor questions:
- would you mind adding a `LICENSE`? :)
- you have [human-readable-ids](https://github.com/JonnyFb421/human-readable-ids) as dependency. I haven't checked the code yet, but upstream looks pretty dead and not used by any other project I found _(only did a quick search)_. Is there any chance you could replace this with something else? Just a friendly question, but it wouldn't be too attracting to depend on a package, which is not used by any other package
- I'd add a modified version of your systemd service file to the `PKGBUILD`
  - would this be fine for you license-wise?

**Comment by Patrick762** [comment]
Hello @frostworx,
thanks for the hint regarding the license. Completely forgot to add it.
If you found another package which could replace the `human-readable-ids` package I'd replace it. I only found two different ones when I was looking.
If you want to use parts of the repo it's fine with me.

**Comment by frostworx** [comment]
Hey @Patrick762,
thanks for the swift reply!
I haven't looked too deep into it, but could it be possible to use the built-in [uuid](https://docs.python.org/3/library/uuid.html) function instead?

I would have tested something like the following patch, but I haven't tested any further functionality yet:

```

--- streamdeckapi/server.py	2023-11-08 20:00:28.542510600 +0100
+++ streamdeckapi/server.py	2023-11-08 20:00:12.000000000 +0100
@@ -11,7 +11,8 @@
 from datetime import datetime
 from typing import List, Dict
 import aiohttp
-import human_readable_ids as hri
+#import human_readable_ids as hri
+import uuid
 from jsonpickle import encode
 from aiohttp import web
 from StreamDeck.DeviceManager import DeviceManager
@@ -546,9 +547,10 @@
             button = get_button(key)
             if not isinstance(button, SDButton):
                 position = get_position(deck, key)
+                my_UUID = uuid.uuid4()
                 new_button = SDButton(
                     {
-                        "uuid": hri.get_new_id().lower().replace(" ", "-"),
+                        "uuid": my_UUID,
                         "device": serial,
                         "position": {"x": position.y_pos, "y": position.x_pos},
                         "svg": DEFAULT_ICON,
```

leads to this output:

```
# $ /usr/bin/streamdeckapi-server
Found 1 Stream Deck(s).
Saved button 0fe3213a-cd43-47b1-a061-0d5dc4117b1f with key 0 to database
Saved button 180f78f9-7f01-43c2-98c0-9399b7ccb63a with key 1 to database
Saved button 465b0c51-caf3-4294-a0b8-362c855ce4e0 with key 2 to database
Saved button dd9fa6e1-094f-4d35-9ec5-864425467917 with key 3 to database
Saved button 12ce83f5-0aa4-4145-af04-84f98bb6d9a2 with key 4 to database
Saved button e13c6bab-df9f-47f3-b1f3-d5e1d5b4eada with key 5 to database
Saved button 7810b8e5-95c4-4c78-93ef-1463f80f109e with key 6 to database
Saved button 9b171303-53cb-4089-a0ba-259ba5b7503d with key 7 to database
Saved button ad981878-33ca-49ce-a029-43b93948f2fa with key 8 to database
Saved button aedb2ba8-b5fc-4bfb-adc7-492676371799 with key 9 to database
Saved button eb5669c7-d107-41fa-8246-27d399e1838f with key 10 to database
Saved button 9a4428c5-097e-4832-92a7-4e8bed4a5fab with key 11 to database
Saved button 08ce6af1-02e7-4b7f-be07-ec7c4642d88e with key 12 to database
Saved button 804d0b10-2c7b-4f86-89e7-fae0a81177ea with key 13 to database
Saved button 5c6f0623-2ced-4dc8-9f93-07d5335889c5 with key 14 to database
...
```

Good to know it is fine for you to recycle parts of the repo :)

**Comment by frostworx** [comment]
Hi again,
Seems like this works as expected. I mapped a light entity to one of the buttons within your addon and it just works.
The light is toggled correctly and the state on the button is updated as expected.

Please let me know if you'd prefer a PR, If the patch is an acceptable change.

**Comment by frostworx** [comment]
Hi again,

The `PKGBUILD` is mostly done, but I just recognized that the path to the sqlite db used is $PWD.

Would you mind adding a command line option for an absolute path to the db and/or using something like `$XDG_CONFIG_HOME/streamdeckapi/streamdeckapi.db` _(when `XDG_CONFIG_HOME` is set)_

Again, thank you for this excellent addon, it integrates seamlessly!

EDIT:
~~alternatively I could simply sed `$XDG_CONFIG_HOME/streamdeckapi/` into https://github.com/Patrick762/streamdeckapi/blob/main/streamdeckapi/const.py#L7C1-L7C8
on `PKGBUILD` side~~

~~I suggest I'll start from here and bump the package when you have make a new release _(makes sense anyway, because of the LICENSE)_~~

EDIT2: scratch that. Of course, the variable needs to be parsed from python side on execution as well _(and fallback if it does not exist)_ I guess adjusting the code is the better approach :)

**Comment by frostworx** [comment]
Hi,
I just released the initial PKGBUILD for v0.0.11, where changes mentioned above are applied via patch:

https://aur.archlinux.org/packages/python-streamdeckapi

The bundled `streamdeckapi.service` is meant to be started as user as in:

```
systemctl --user start streamdeckapi
systemctl --user enable streamdeckapi
```
I also created a fork and will open a PR with the patch applied shortly.
I'd understand if you'd reject it, as I'm not too much into python and didn't spend much time into writing nice code :)

**Comment by Patrick762** [comment]
> Hey @Patrick762, thanks for the swift reply! I haven't looked too deep into it, but could it be possible to use the built-in [uuid](https://docs.python.org/3/library/uuid.html) function instead?
> 
> I would have tested something like the following patch, but I haven't tested any further functionality yet:
> 
> ```
> 
> --- streamdeckapi/server.py	2023-11-08 20:00:28.542510600 +0100
> +++ streamdeckapi/server.py	2023-11-08 20:00:12.000000000 +0100
> @@ -11,7 +11,8 @@
>  from datetime import datetime
>  from typing import List, Dict
>  import aiohttp
> -import human_readable_ids as hri
> +#import human_readable_ids as hri
> +import uuid
>  from jsonpickle import encode
>  from aiohttp import web
>  from StreamDeck.DeviceManager import DeviceManager
> @@ -546,9 +547,10 @@
>              button = get_button(key)
>              if not isinstance(button, SDButton):
>                  position = get_position(deck, key)
> +                my_UUID = uuid.uuid4()
>                  new_button = SDButton(
>                      {
> -                        "uuid": hri.get_new_id().lower().replace(" ", "-"),
> +                        "uuid": my_UUID,
>                          "device": serial,
>                          "position": {"x": position.y_pos, "y": position.x_pos},
>                          "svg": DEFAULT_ICON,
> ```
> 
> leads to this output:
> 
> ```
> # $ /usr/bin/streamdeckapi-server
> Found 1 Stream Deck(s).
> Saved button 0fe3213a-cd43-47b1-a061-0d5dc4117b1f with key 0 to database
> Saved button 180f78f9-7f01-43c2-98c0-9399b7ccb63a with key 1 to database
> Saved button 465b0c51-caf3-4294-a0b8-362c855ce4e0 with key 2 to database
> Saved button dd9fa6e1-094f-4d35-9ec5-864425467917 with key 3 to database
> Saved button 12ce83f5-0aa4-4145-af04-84f98bb6d9a2 with key 4 to database
> Saved button e13c6bab-df9f-47f3-b1f3-d5e1d5b4eada with key 5 to database
> Saved button 7810b8e5-95c4-4c78-93ef-1463f80f109e with key 6 to database
> Saved button 9b171303-53cb-4089-a0ba-259ba5b7503d with key 7 to database
> Saved button ad981878-33ca-49ce-a029-43b93948f2fa with key 8 to database
> Saved button aedb2ba8-b5fc-4bfb-adc7-492676371799 with key 9 to database
> Saved button eb5669c7-d107-41fa-8246-27d399e1838f with key 10 to database
> Saved button 9a4428c5-097e-4832-92a7-4e8bed4a5fab with key 11 to database
> Saved button 08ce6af1-02e7-4b7f-be07-ec7c4642d88e with key 12 to database
> Saved button 804d0b10-2c7b-4f86-89e7-fae0a81177ea with key 13 to database
> Saved button 5c6f0623-2ced-4dc8-9f93-07d5335889c5 with key 14 to database
> ...
> ```
> 
> Good to know it is fine for you to recycle parts of the repo :)

The only reason I chose the human-readable-ids package was, as the name implies, that those ids are easily readable for humans.
Normal uuids are much harder to see on the small screens of the Stream Deck, which is the fallback for configuring the keys in Home Assistant.
Another option would be to show the key position on screen instead of the id.

**Comment by frostworx** [comment]
ic
